//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AstuteServiceReference
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseOfArrayOfGroupNameEntityTd6MonVm", Namespace="http://schemas.datacontract.org/2004/07/Avanzar.ServicePlatform.Contracts.Ccp.Ent" +
        "ities.AstuteServiceV2")]
    public partial class ResponseOfArrayOfGroupNameEntityTd6MonVm : object
    {
        
        private AstuteServiceReference.GroupNameEntity[] DataField;
        
        private AstuteServiceReference.Result ResultField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AstuteServiceReference.GroupNameEntity[] Data
        {
            get
            {
                return this.DataField;
            }
            set
            {
                this.DataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AstuteServiceReference.Result Result
        {
            get
            {
                return this.ResultField;
            }
            set
            {
                this.ResultField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Result", Namespace="http://schemas.datacontract.org/2004/07/Avanzar.ServicePlatform.Contracts.Ccp.Ent" +
        "ities.AstuteServiceV2")]
    public partial class Result : object
    {
        
        private AstuteServiceReference.CompletionCode CompletionCodeField;
        
        private AstuteServiceReference.ReasonCode ReasonCodeField;
        
        private string ReasonDescriptionField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AstuteServiceReference.CompletionCode CompletionCode
        {
            get
            {
                return this.CompletionCodeField;
            }
            set
            {
                this.CompletionCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AstuteServiceReference.ReasonCode ReasonCode
        {
            get
            {
                return this.ReasonCodeField;
            }
            set
            {
                this.ReasonCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReasonDescription
        {
            get
            {
                return this.ReasonDescriptionField;
            }
            set
            {
                this.ReasonDescriptionField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GroupNameEntity", Namespace="http://schemas.datacontract.org/2004/07/Avanzar.ServicePlatform.Contracts.Ccp.Ent" +
        "ities.AstuteServiceV2")]
    public partial class GroupNameEntity : object
    {
        
        private int GroupIdField;
        
        private string GroupNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int GroupId
        {
            get
            {
                return this.GroupIdField;
            }
            set
            {
                this.GroupIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GroupName
        {
            get
            {
                return this.GroupNameField;
            }
            set
            {
                this.GroupNameField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompletionCode", Namespace="http://schemas.datacontract.org/2004/07/Avanzar.ServicePlatform.Contracts.Ccp.Enu" +
        "ms")]
    public enum CompletionCode : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Success = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Failure = 1,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ReasonCode", Namespace="http://schemas.datacontract.org/2004/07/Avanzar.ServicePlatform.Contracts.Ccp.Enu" +
        "ms")]
    public enum ReasonCode : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Unknown = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GeneralSQLError = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UserNotFound = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidPassword = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidLOAStatus = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PasswordChangeFailed = 6,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NoProductsAvailable = 7,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NoProductSectorsAvailable = 8,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidUserState = 9,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UserAccountLocked = 10,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidIdentityType = 11,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidRootState = 14,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidBOState = 15,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ProductRequestInsertFailed = 17,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidParentState = 18,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidGroupState = 19,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        TransactionalItemInsertUpdateFailed = 20,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidFieldSpecification = 21,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ObjectNotFound = 22,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        RestrictedFieldCannotBeModified = 23,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UserIdentityAlreadyExists = 27,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DefaultProductAssignementFailed = 28,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UserIdentityPartiallyExists = 29,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UniqueNameRequired = 30,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InternalCounterUpdateFailed = 31,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ObjectInsertUpdateFailed = 32,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InternalCounterFetchFailed = 33,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        RemoveTempObjectFailed = 34,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GroupProfileUpdateFailed = 38,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        RestrictedViewRequest = 42,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UserInfoFetchFailed = 43,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ObjectDeleteFailed = 48,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidItemRequest = 57,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidDebtorsAccount = 61,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ProductNotAssignedToUser = 70,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UserInsertIntoVettinVatFailed = 72,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PasswordResetFailed = 74,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PassworDeliveryFailed = 75,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UserNotFoundOnLOARegister = 76,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LateResponseReceived = 80,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        TransactionLimitIncreaseFailed = 84,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        HeadersUnavailable = 90,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        HeaderUnavailable = 91,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ContentProviderCodeNotFound = 92,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ContentUnavailable = 93,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        BillingBandAlreadyAssignedToBillingObject = 94,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UserProfileUpdateFailed = 95,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        BillingObjectProfileUpdateFailed = 96,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        BillingBandNotAssignedToBillingObject = 97,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        TransactionLimitReached = 100,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ProductNotAssignedToBillingObject = 101,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        TransactionCountInArrears = 102,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        TransactionLimitExceede = 103,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MQDeliveryFailed = 105,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ErrorQueueDeliveryFailed = 106,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        RequestIDNotFound = 107,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ClientApplicationinformationCouldNotBeRetrieved = 108,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DMSAccountUpdateFailed = 110,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DMSTransactionIssueFailed = 111,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MailItemProcessFailed = 112,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MailItemInsertFailed = 113,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        EmailDelivered = 114,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        TransactionExceed = 115,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidAccountType = 151,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DMSInterfaceCallProcessFailed = 152,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DMSSystemReturnedFailureCode = 153,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ExcessTransactionCountResetFailed = 160,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        BillingObjectInsertNewHistoryMonthFailed = 161,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        TransactionCountCarryOverFailed = 162,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        TransactionCountSetForCurrentMonthFailed = 163,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MaximumMonthHistoryUpdateFailed = 165,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DuplicateRequestIDFound = 170,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DuplicateBatchIDFound = 171,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UsernameExists = 200,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NoChildrenOrInvalidObject = 201,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AuditEntryItemFailed = 202,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ReportHit = 210,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        EndDateBeforeStartDate = 211,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NULLDates = 212,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NoWeekdaysSelected = 213,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidParameters = 214,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NoMonthsSelected = 215,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        OnlyOneContentProviderAllowed = 216,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NoPolicyNumberSupplied = 217,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        OnlyFSEUserMayChangeSysUserFlag = 218,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UnauthorisedNonSystemUser = 219,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SystemUserNotAuthorised = 220,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AssistantNotAuthorisedToTransactOnBehalfOfPrimaryUser = 221,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PasswordExpiring = 222,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PasswordExpired = 223,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PasswordExpiringOneDay = 224,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PasswordExpiringTwoDays = 225,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PasswordExpiringThreeDays = 226,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PasswordExpiringFourDays = 227,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PasswordExpiringFiveDays = 228,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UserNotFoundInLOAorCIRRegistry = 1000,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UserValidStatusOnCIR = 1001,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UserPendingStatusOnCIR = 1002,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UserSuspendedStatusOnCIR = 1003,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UserRejectedStatusOnCIR = 1004,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MSXMLException = 3006,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidTransactionRequest = 3009,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidTransactionResponse = 3010,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        QueueConnectionError = 3011,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        QueueDeliveryError = 3012,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        QueueReceiveError = 3013,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        TimeoutWaitingForMessage = 3014,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InternalFSEError = 3015,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MailboxCleanupComplete = 3016,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        RequestCleanupComplete = 3017,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LOAUpdateComplete = 3018,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LOACleanupComplete = 3019,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        RootCleanupComplete = 3020,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GroupCleanupComplete = 3021,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        BillingObjectCleanupComplete = 3022,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UserCleanupComplete = 3023,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AuditArchiveComplete = 3024,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AuditArchiveFailed = 3025,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SMSAdminTaskInvalid = 3030,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SpecialBONotAllocatedForSMS = 3031,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        BONotAllocatedForSMS = 3032,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PointOfSalesDenied = 3033,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NoProvidersForSector = 3039,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UserNotFoundOnFSBRegister = 3041,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UserFSPInactive = 3042,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UserGroupFSPNumberNull = 999888,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        No_Consent = 3044,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Consent_Revoked = 3045,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Consent_Expired = 3046,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Duplicate_Consent = 3047,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        User_CCMS_Disabled = 3048,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PreAttached_Consent_Not_Applicable = 3049,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        OldLogMethodCall = 9999,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseOfArrayOfParentNameEntityTd6MonVm", Namespace="http://schemas.datacontract.org/2004/07/Avanzar.ServicePlatform.Contracts.Ccp.Ent" +
        "ities.AstuteServiceV2")]
    public partial class ResponseOfArrayOfParentNameEntityTd6MonVm : object
    {
        
        private AstuteServiceReference.ParentNameEntity[] DataField;
        
        private AstuteServiceReference.Result ResultField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AstuteServiceReference.ParentNameEntity[] Data
        {
            get
            {
                return this.DataField;
            }
            set
            {
                this.DataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AstuteServiceReference.Result Result
        {
            get
            {
                return this.ResultField;
            }
            set
            {
                this.ResultField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ParentNameEntity", Namespace="http://schemas.datacontract.org/2004/07/Avanzar.ServicePlatform.Contracts.Ccp.Ent" +
        "ities.AstuteServiceV2")]
    public partial class ParentNameEntity : object
    {
        
        private string ParentProfileNameField;
        
        private int ProfileIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ParentProfileName
        {
            get
            {
                return this.ParentProfileNameField;
            }
            set
            {
                this.ParentProfileNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ProfileId
        {
            get
            {
                return this.ProfileIdField;
            }
            set
            {
                this.ProfileIdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CcpRequestDetails", Namespace="http://schemas.datacontract.org/2004/07/Avanzar.ServicePlatform.Contracts.Ccp.Ent" +
        "ities")]
    public partial class CcpRequestDetails : object
    {
        
        private string CellNumberField;
        
        private System.Nullable<System.DateTime> DateOfBirthField;
        
        private string EmailAddressField;
        
        private string FirstNameField;
        
        private System.Nullable<int> HighVolumeField;
        
        private string IdNumberField;
        
        private System.Nullable<AstuteServiceReference.IdType> IdTypeField;
        
        private string InitialsField;
        
        private System.Nullable<System.Guid> MyClientGuidField;
        
        private int MyClientIdField;
        
        private System.Nullable<int> OnBehalfOfProfileIdField;
        
        private bool OverrideDigitalConsentField;
        
        private AstuteServiceReference.ProviderDetail[] RequestDetailsField;
        
        private bool RequestDigitalConsentField;
        
        private string SurnameField;
        
        private int TransactingGroupIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CellNumber
        {
            get
            {
                return this.CellNumberField;
            }
            set
            {
                this.CellNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DateOfBirth
        {
            get
            {
                return this.DateOfBirthField;
            }
            set
            {
                this.DateOfBirthField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmailAddress
        {
            get
            {
                return this.EmailAddressField;
            }
            set
            {
                this.EmailAddressField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName
        {
            get
            {
                return this.FirstNameField;
            }
            set
            {
                this.FirstNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> HighVolume
        {
            get
            {
                return this.HighVolumeField;
            }
            set
            {
                this.HighVolumeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdNumber
        {
            get
            {
                return this.IdNumberField;
            }
            set
            {
                this.IdNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<AstuteServiceReference.IdType> IdType
        {
            get
            {
                return this.IdTypeField;
            }
            set
            {
                this.IdTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Initials
        {
            get
            {
                return this.InitialsField;
            }
            set
            {
                this.InitialsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.Guid> MyClientGuid
        {
            get
            {
                return this.MyClientGuidField;
            }
            set
            {
                this.MyClientGuidField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MyClientId
        {
            get
            {
                return this.MyClientIdField;
            }
            set
            {
                this.MyClientIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> OnBehalfOfProfileId
        {
            get
            {
                return this.OnBehalfOfProfileIdField;
            }
            set
            {
                this.OnBehalfOfProfileIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool OverrideDigitalConsent
        {
            get
            {
                return this.OverrideDigitalConsentField;
            }
            set
            {
                this.OverrideDigitalConsentField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AstuteServiceReference.ProviderDetail[] RequestDetails
        {
            get
            {
                return this.RequestDetailsField;
            }
            set
            {
                this.RequestDetailsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool RequestDigitalConsent
        {
            get
            {
                return this.RequestDigitalConsentField;
            }
            set
            {
                this.RequestDigitalConsentField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Surname
        {
            get
            {
                return this.SurnameField;
            }
            set
            {
                this.SurnameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TransactingGroupId
        {
            get
            {
                return this.TransactingGroupIdField;
            }
            set
            {
                this.TransactingGroupIdField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="IdType", Namespace="http://schemas.datacontract.org/2004/07/Avanzar.ServicePlatform.Contracts.Enums")]
    public enum IdType : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SouthAfrican = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Namibian = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Other = 3,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProviderDetail", Namespace="http://schemas.datacontract.org/2004/07/Avanzar.ServicePlatform.Contracts.Ccp.Ent" +
        "ities")]
    public partial class ProviderDetail : object
    {
        
        private string PolicyNumberField;
        
        private string ProviderCodeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PolicyNumber
        {
            get
            {
                return this.PolicyNumberField;
            }
            set
            {
                this.PolicyNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProviderCode
        {
            get
            {
                return this.ProviderCodeField;
            }
            set
            {
                this.ProviderCodeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Response", Namespace="http://schemas.datacontract.org/2004/07/Avanzar.ServicePlatform.Contracts.Ccp.Ent" +
        "ities.AstuteServiceV2")]
    public partial class Response : object
    {
        
        private AstuteServiceReference.Result ResultField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AstuteServiceReference.Result Result
        {
            get
            {
                return this.ResultField;
            }
            set
            {
                this.ResultField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseOfArrayOfMessageHeaderTd6MonVm", Namespace="http://schemas.datacontract.org/2004/07/Avanzar.ServicePlatform.Contracts.Ccp.Ent" +
        "ities.AstuteServiceV2")]
    public partial class ResponseOfArrayOfMessageHeaderTd6MonVm : object
    {
        
        private AstuteServiceReference.MessageHeader[] DataField;
        
        private AstuteServiceReference.Result ResultField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AstuteServiceReference.MessageHeader[] Data
        {
            get
            {
                return this.DataField;
            }
            set
            {
                this.DataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AstuteServiceReference.Result Result
        {
            get
            {
                return this.ResultField;
            }
            set
            {
                this.ResultField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MessageHeader", Namespace="http://schemas.datacontract.org/2004/07/Avanzar.ServicePlatform.Contracts.Ccp.Ent" +
        "ities.AstuteServiceV2")]
    public partial class MessageHeader : object
    {
        
        private System.Nullable<System.Guid> CombineIdField;
        
        private sbyte CompleteCountField;
        
        private string DisplayStringField;
        
        private System.Guid MessageIdField;
        
        private AstuteServiceReference.Provider[] NoReplyProviderField;
        
        private string ReferenceNoField;
        
        private AstuteServiceReference.Provider[] ReplyProviderField;
        
        private AstuteServiceReference.CcpProduct RequestProductField;
        
        private sbyte ResponseCountField;
        
        private string ResultDescriptionField;
        
        private System.Nullable<int> ResultInfoCodeField;
        
        private System.Nullable<System.DateTime> TimestampCompletedField;
        
        private System.DateTime TimestampIssuedField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.Guid> CombineId
        {
            get
            {
                return this.CombineIdField;
            }
            set
            {
                this.CombineIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public sbyte CompleteCount
        {
            get
            {
                return this.CompleteCountField;
            }
            set
            {
                this.CompleteCountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DisplayString
        {
            get
            {
                return this.DisplayStringField;
            }
            set
            {
                this.DisplayStringField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid MessageId
        {
            get
            {
                return this.MessageIdField;
            }
            set
            {
                this.MessageIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AstuteServiceReference.Provider[] NoReplyProvider
        {
            get
            {
                return this.NoReplyProviderField;
            }
            set
            {
                this.NoReplyProviderField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReferenceNo
        {
            get
            {
                return this.ReferenceNoField;
            }
            set
            {
                this.ReferenceNoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AstuteServiceReference.Provider[] ReplyProvider
        {
            get
            {
                return this.ReplyProviderField;
            }
            set
            {
                this.ReplyProviderField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AstuteServiceReference.CcpProduct RequestProduct
        {
            get
            {
                return this.RequestProductField;
            }
            set
            {
                this.RequestProductField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public sbyte ResponseCount
        {
            get
            {
                return this.ResponseCountField;
            }
            set
            {
                this.ResponseCountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ResultDescription
        {
            get
            {
                return this.ResultDescriptionField;
            }
            set
            {
                this.ResultDescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> ResultInfoCode
        {
            get
            {
                return this.ResultInfoCodeField;
            }
            set
            {
                this.ResultInfoCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> TimestampCompleted
        {
            get
            {
                return this.TimestampCompletedField;
            }
            set
            {
                this.TimestampCompletedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime TimestampIssued
        {
            get
            {
                return this.TimestampIssuedField;
            }
            set
            {
                this.TimestampIssuedField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Provider", Namespace="http://schemas.datacontract.org/2004/07/Avanzar.ServicePlatform.Contracts.Ccp.Ent" +
        "ities.AstuteServiceV2")]
    public partial class Provider : object
    {
        
        private string ProviderCodeField;
        
        private string ProviderNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProviderCode
        {
            get
            {
                return this.ProviderCodeField;
            }
            set
            {
                this.ProviderCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProviderName
        {
            get
            {
                return this.ProviderNameField;
            }
            set
            {
                this.ProviderNameField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CcpProduct", Namespace="http://schemas.datacontract.org/2004/07/Avanzar.ServicePlatform.Contracts.Ccp.Enu" +
        "ms")]
    public enum CcpProduct : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LifeAndRisk = 280,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UnitTrust = 281,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LinkedInvestment = 282,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        EmployeeBenefit = 283,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MedicalAid = 284,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseOfMessageHeaderTd6MonVm", Namespace="http://schemas.datacontract.org/2004/07/Avanzar.ServicePlatform.Contracts.Ccp.Ent" +
        "ities.AstuteServiceV2")]
    public partial class ResponseOfMessageHeaderTd6MonVm : object
    {
        
        private AstuteServiceReference.MessageHeader DataField;
        
        private AstuteServiceReference.Result ResultField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AstuteServiceReference.MessageHeader Data
        {
            get
            {
                return this.DataField;
            }
            set
            {
                this.DataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AstuteServiceReference.Result Result
        {
            get
            {
                return this.ResultField;
            }
            set
            {
                this.ResultField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseOfMessageContentTd6MonVm", Namespace="http://schemas.datacontract.org/2004/07/Avanzar.ServicePlatform.Contracts.Ccp.Ent" +
        "ities.AstuteServiceV2")]
    public partial class ResponseOfMessageContentTd6MonVm : object
    {
        
        private AstuteServiceReference.MessageContent DataField;
        
        private AstuteServiceReference.Result ResultField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AstuteServiceReference.MessageContent Data
        {
            get
            {
                return this.DataField;
            }
            set
            {
                this.DataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AstuteServiceReference.Result Result
        {
            get
            {
                return this.ResultField;
            }
            set
            {
                this.ResultField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MessageContent", Namespace="http://schemas.datacontract.org/2004/07/Avanzar.ServicePlatform.Contracts.Ccp.Ent" +
        "ities.AstuteServiceV2")]
    public partial class MessageContent : object
    {
        
        private AstuteServiceReference.Content[] MessageBodyField;
        
        private AstuteServiceReference.MessageHeader MessageHeaderField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AstuteServiceReference.Content[] MessageBody
        {
            get
            {
                return this.MessageBodyField;
            }
            set
            {
                this.MessageBodyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AstuteServiceReference.MessageHeader MessageHeader
        {
            get
            {
                return this.MessageHeaderField;
            }
            set
            {
                this.MessageHeaderField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Content", Namespace="http://schemas.datacontract.org/2004/07/Avanzar.ServicePlatform.Contracts.Ccp.Ent" +
        "ities.AstuteServiceV2")]
    public partial class Content : object
    {
        
        private string ContentSchemaRefField;
        
        private string ProviderCodeField;
        
        private string ValueField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ContentSchemaRef
        {
            get
            {
                return this.ContentSchemaRefField;
            }
            set
            {
                this.ContentSchemaRefField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProviderCode
        {
            get
            {
                return this.ProviderCodeField;
            }
            set
            {
                this.ProviderCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Value
        {
            get
            {
                return this.ValueField;
            }
            set
            {
                this.ValueField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseOfProductSectorSetTd6MonVm", Namespace="http://schemas.datacontract.org/2004/07/Avanzar.ServicePlatform.Contracts.Ccp.Ent" +
        "ities.AstuteServiceV2")]
    public partial class ResponseOfProductSectorSetTd6MonVm : object
    {
        
        private AstuteServiceReference.ProductSectorSet DataField;
        
        private AstuteServiceReference.Result ResultField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AstuteServiceReference.ProductSectorSet Data
        {
            get
            {
                return this.DataField;
            }
            set
            {
                this.DataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AstuteServiceReference.Result Result
        {
            get
            {
                return this.ResultField;
            }
            set
            {
                this.ResultField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProductSectorSet", Namespace="http://schemas.datacontract.org/2004/07/Avanzar.ServicePlatform.Contracts.Ccp.Ent" +
        "ities.AstuteServiceV2")]
    public partial class ProductSectorSet : object
    {
        
        private AstuteServiceReference.ProductSector[] ProductSectorField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AstuteServiceReference.ProductSector[] ProductSector
        {
            get
            {
                return this.ProductSectorField;
            }
            set
            {
                this.ProductSectorField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProductSector", Namespace="http://schemas.datacontract.org/2004/07/Avanzar.ServicePlatform.Contracts.Ccp.Ent" +
        "ities.AstuteServiceV2")]
    public partial class ProductSector : object
    {
        
        private string SectorCodeField;
        
        private string ValueField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SectorCode
        {
            get
            {
                return this.SectorCodeField;
            }
            set
            {
                this.SectorCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Value
        {
            get
            {
                return this.ValueField;
            }
            set
            {
                this.ValueField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseOfProductSetTd6MonVm", Namespace="http://schemas.datacontract.org/2004/07/Avanzar.ServicePlatform.Contracts.Ccp.Ent" +
        "ities.AstuteServiceV2")]
    public partial class ResponseOfProductSetTd6MonVm : object
    {
        
        private AstuteServiceReference.ProductSet DataField;
        
        private AstuteServiceReference.Result ResultField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AstuteServiceReference.ProductSet Data
        {
            get
            {
                return this.DataField;
            }
            set
            {
                this.DataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AstuteServiceReference.Result Result
        {
            get
            {
                return this.ResultField;
            }
            set
            {
                this.ResultField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProductSet", Namespace="http://schemas.datacontract.org/2004/07/Avanzar.ServicePlatform.Contracts.Ccp.Ent" +
        "ities.AstuteServiceV2")]
    public partial class ProductSet : object
    {
        
        private AstuteServiceReference.Product[] ProductField;
        
        private string SectorCodeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AstuteServiceReference.Product[] Product
        {
            get
            {
                return this.ProductField;
            }
            set
            {
                this.ProductField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SectorCode
        {
            get
            {
                return this.SectorCodeField;
            }
            set
            {
                this.SectorCodeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Product", Namespace="http://schemas.datacontract.org/2004/07/Avanzar.ServicePlatform.Contracts.Ccp.Ent" +
        "ities.AstuteServiceV2")]
    public partial class Product : object
    {
        
        private AstuteServiceReference.CcpProduct ProductCodeField;
        
        private string ValueField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AstuteServiceReference.CcpProduct ProductCode
        {
            get
            {
                return this.ProductCodeField;
            }
            set
            {
                this.ProductCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Value
        {
            get
            {
                return this.ValueField;
            }
            set
            {
                this.ValueField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseOfContentProviderSetTd6MonVm", Namespace="http://schemas.datacontract.org/2004/07/Avanzar.ServicePlatform.Contracts.Ccp.Ent" +
        "ities.AstuteServiceV2")]
    public partial class ResponseOfContentProviderSetTd6MonVm : object
    {
        
        private AstuteServiceReference.ContentProviderSet DataField;
        
        private AstuteServiceReference.Result ResultField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AstuteServiceReference.ContentProviderSet Data
        {
            get
            {
                return this.DataField;
            }
            set
            {
                this.DataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AstuteServiceReference.Result Result
        {
            get
            {
                return this.ResultField;
            }
            set
            {
                this.ResultField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ContentProviderSet", Namespace="http://schemas.datacontract.org/2004/07/Avanzar.ServicePlatform.Contracts.Ccp.Ent" +
        "ities.AstuteServiceV2")]
    public partial class ContentProviderSet : object
    {
        
        private AstuteServiceReference.CcpProduct ProductCodeField;
        
        private AstuteServiceReference.Provider[] ProviderField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AstuteServiceReference.CcpProduct ProductCode
        {
            get
            {
                return this.ProductCodeField;
            }
            set
            {
                this.ProductCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AstuteServiceReference.Provider[] Provider
        {
            get
            {
                return this.ProviderField;
            }
            set
            {
                this.ProviderField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseOfWebContentTd6MonVm", Namespace="http://schemas.datacontract.org/2004/07/Avanzar.ServicePlatform.Contracts.Ccp.Ent" +
        "ities.AstuteServiceV2")]
    public partial class ResponseOfWebContentTd6MonVm : object
    {
        
        private AstuteServiceReference.WebContent DataField;
        
        private AstuteServiceReference.Result ResultField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AstuteServiceReference.WebContent Data
        {
            get
            {
                return this.DataField;
            }
            set
            {
                this.DataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AstuteServiceReference.Result Result
        {
            get
            {
                return this.ResultField;
            }
            set
            {
                this.ResultField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WebContent", Namespace="http://schemas.datacontract.org/2004/07/Avanzar.ServicePlatform.Contracts.Ccp.Ent" +
        "ities.AstuteServiceV2")]
    public partial class WebContent : object
    {
        
        private string ValueField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Value
        {
            get
            {
                return this.ValueField;
            }
            set
            {
                this.ValueField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseOfArrayOfMessageContentTd6MonVm", Namespace="http://schemas.datacontract.org/2004/07/Avanzar.ServicePlatform.Contracts.Ccp.Ent" +
        "ities.AstuteServiceV2")]
    public partial class ResponseOfArrayOfMessageContentTd6MonVm : object
    {
        
        private AstuteServiceReference.MessageContent[] DataField;
        
        private AstuteServiceReference.Result ResultField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AstuteServiceReference.MessageContent[] Data
        {
            get
            {
                return this.DataField;
            }
            set
            {
                this.DataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public AstuteServiceReference.Result Result
        {
            get
            {
                return this.ResultField;
            }
            set
            {
                this.ResultField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AstuteServiceReference.IAstuteServiceV3")]
    public interface IAstuteServiceV3
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAstuteServiceV3/GetProfileGroups", ReplyAction="http://tempuri.org/IAstuteServiceV3/GetProfileGroupsResponse")]
        System.Threading.Tasks.Task<AstuteServiceReference.ResponseOfArrayOfGroupNameEntityTd6MonVm> GetProfileGroupsAsync(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAstuteServiceV3/GetPrimaryUsers", ReplyAction="http://tempuri.org/IAstuteServiceV3/GetPrimaryUsersResponse")]
        System.Threading.Tasks.Task<AstuteServiceReference.ResponseOfArrayOfParentNameEntityTd6MonVm> GetPrimaryUsersAsync(string username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAstuteServiceV3/PerformCcpRequest", ReplyAction="http://tempuri.org/IAstuteServiceV3/PerformCcpRequestResponse")]
        System.Threading.Tasks.Task<AstuteServiceReference.Response> PerformCcpRequestAsync(AstuteServiceReference.CcpRequestDetails requestDetails, System.Nullable<System.Guid> messageId, System.Nullable<System.Guid> combineId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAstuteServiceV3/PerformIntermediaryRequest", ReplyAction="http://tempuri.org/IAstuteServiceV3/PerformIntermediaryRequestResponse")]
        System.Threading.Tasks.Task<AstuteServiceReference.Response> PerformIntermediaryRequestAsync(AstuteServiceReference.CcpRequestDetails requestDetails, System.Nullable<System.Guid> messageId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAstuteServiceV3/PerformMedicalRequest", ReplyAction="http://tempuri.org/IAstuteServiceV3/PerformMedicalRequestResponse")]
        System.Threading.Tasks.Task<AstuteServiceReference.Response> PerformMedicalRequestAsync(AstuteServiceReference.CcpRequestDetails requestDetails, System.Nullable<System.Guid> messageId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAstuteServiceV3/GetMessageHeaders", ReplyAction="http://tempuri.org/IAstuteServiceV3/GetMessageHeadersResponse")]
        System.Threading.Tasks.Task<AstuteServiceReference.ResponseOfArrayOfMessageHeaderTd6MonVm> GetMessageHeadersAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAstuteServiceV3/GetMessageHeader", ReplyAction="http://tempuri.org/IAstuteServiceV3/GetMessageHeaderResponse")]
        System.Threading.Tasks.Task<AstuteServiceReference.ResponseOfMessageHeaderTd6MonVm> GetMessageHeaderAsync(System.Guid messageId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAstuteServiceV3/GetMessageContent", ReplyAction="http://tempuri.org/IAstuteServiceV3/GetMessageContentResponse")]
        System.Threading.Tasks.Task<AstuteServiceReference.ResponseOfMessageContentTd6MonVm> GetMessageContentAsync(System.Guid messageId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAstuteServiceV3/GetProductSectorSet", ReplyAction="http://tempuri.org/IAstuteServiceV3/GetProductSectorSetResponse")]
        System.Threading.Tasks.Task<AstuteServiceReference.ResponseOfProductSectorSetTd6MonVm> GetProductSectorSetAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAstuteServiceV3/GetProductSet", ReplyAction="http://tempuri.org/IAstuteServiceV3/GetProductSetResponse")]
        System.Threading.Tasks.Task<AstuteServiceReference.ResponseOfProductSetTd6MonVm> GetProductSetAsync(string sectorCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAstuteServiceV3/GetContentProviderSet", ReplyAction="http://tempuri.org/IAstuteServiceV3/GetContentProviderSetResponse")]
        System.Threading.Tasks.Task<AstuteServiceReference.ResponseOfContentProviderSetTd6MonVm> GetContentProviderSetAsync(AstuteServiceReference.CcpProduct productCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAstuteServiceV3/ChangePassword", ReplyAction="http://tempuri.org/IAstuteServiceV3/ChangePasswordResponse")]
        System.Threading.Tasks.Task<AstuteServiceReference.Response> ChangePasswordAsync(string oldPassword, string newPassword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAstuteServiceV3/GetWebMessageContent", ReplyAction="http://tempuri.org/IAstuteServiceV3/GetWebMessageContentResponse")]
        System.Threading.Tasks.Task<AstuteServiceReference.ResponseOfWebContentTd6MonVm> GetWebMessageContentAsync(System.Guid messageId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAstuteServiceV3/GetCombinedMessageHeader", ReplyAction="http://tempuri.org/IAstuteServiceV3/GetCombinedMessageHeaderResponse")]
        System.Threading.Tasks.Task<AstuteServiceReference.ResponseOfArrayOfMessageHeaderTd6MonVm> GetCombinedMessageHeaderAsync(System.Guid messageId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAstuteServiceV3/GetCombinedMessageContent", ReplyAction="http://tempuri.org/IAstuteServiceV3/GetCombinedMessageContentResponse")]
        System.Threading.Tasks.Task<AstuteServiceReference.ResponseOfArrayOfMessageContentTd6MonVm> GetCombinedMessageContentAsync(System.Guid messageId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public interface IAstuteServiceV3Channel : AstuteServiceReference.IAstuteServiceV3, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public partial class AstuteServiceV3Client : System.ServiceModel.ClientBase<AstuteServiceReference.IAstuteServiceV3>, AstuteServiceReference.IAstuteServiceV3
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public AstuteServiceV3Client() : 
                base(AstuteServiceV3Client.GetDefaultBinding(), AstuteServiceV3Client.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.WSHttpBinding_IAstuteServiceV3.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public AstuteServiceV3Client(EndpointConfiguration endpointConfiguration) : 
                base(AstuteServiceV3Client.GetBindingForEndpoint(endpointConfiguration), AstuteServiceV3Client.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public AstuteServiceV3Client(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(AstuteServiceV3Client.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public AstuteServiceV3Client(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(AstuteServiceV3Client.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public AstuteServiceV3Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<AstuteServiceReference.ResponseOfArrayOfGroupNameEntityTd6MonVm> GetProfileGroupsAsync(string username)
        {
            return base.Channel.GetProfileGroupsAsync(username);
        }
        
        public System.Threading.Tasks.Task<AstuteServiceReference.ResponseOfArrayOfParentNameEntityTd6MonVm> GetPrimaryUsersAsync(string username)
        {
            return base.Channel.GetPrimaryUsersAsync(username);
        }
        
        public System.Threading.Tasks.Task<AstuteServiceReference.Response> PerformCcpRequestAsync(AstuteServiceReference.CcpRequestDetails requestDetails, System.Nullable<System.Guid> messageId, System.Nullable<System.Guid> combineId)
        {
            return base.Channel.PerformCcpRequestAsync(requestDetails, messageId, combineId);
        }
        
        public System.Threading.Tasks.Task<AstuteServiceReference.Response> PerformIntermediaryRequestAsync(AstuteServiceReference.CcpRequestDetails requestDetails, System.Nullable<System.Guid> messageId)
        {
            return base.Channel.PerformIntermediaryRequestAsync(requestDetails, messageId);
        }
        
        public System.Threading.Tasks.Task<AstuteServiceReference.Response> PerformMedicalRequestAsync(AstuteServiceReference.CcpRequestDetails requestDetails, System.Nullable<System.Guid> messageId)
        {
            return base.Channel.PerformMedicalRequestAsync(requestDetails, messageId);
        }
        
        public System.Threading.Tasks.Task<AstuteServiceReference.ResponseOfArrayOfMessageHeaderTd6MonVm> GetMessageHeadersAsync()
        {
            return base.Channel.GetMessageHeadersAsync();
        }
        
        public System.Threading.Tasks.Task<AstuteServiceReference.ResponseOfMessageHeaderTd6MonVm> GetMessageHeaderAsync(System.Guid messageId)
        {
            return base.Channel.GetMessageHeaderAsync(messageId);
        }
        
        public System.Threading.Tasks.Task<AstuteServiceReference.ResponseOfMessageContentTd6MonVm> GetMessageContentAsync(System.Guid messageId)
        {
            return base.Channel.GetMessageContentAsync(messageId);
        }
        
        public System.Threading.Tasks.Task<AstuteServiceReference.ResponseOfProductSectorSetTd6MonVm> GetProductSectorSetAsync()
        {
            return base.Channel.GetProductSectorSetAsync();
        }
        
        public System.Threading.Tasks.Task<AstuteServiceReference.ResponseOfProductSetTd6MonVm> GetProductSetAsync(string sectorCode)
        {
            return base.Channel.GetProductSetAsync(sectorCode);
        }
        
        public System.Threading.Tasks.Task<AstuteServiceReference.ResponseOfContentProviderSetTd6MonVm> GetContentProviderSetAsync(AstuteServiceReference.CcpProduct productCode)
        {
            return base.Channel.GetContentProviderSetAsync(productCode);
        }
        
        public System.Threading.Tasks.Task<AstuteServiceReference.Response> ChangePasswordAsync(string oldPassword, string newPassword)
        {
            return base.Channel.ChangePasswordAsync(oldPassword, newPassword);
        }
        
        public System.Threading.Tasks.Task<AstuteServiceReference.ResponseOfWebContentTd6MonVm> GetWebMessageContentAsync(System.Guid messageId)
        {
            return base.Channel.GetWebMessageContentAsync(messageId);
        }
        
        public System.Threading.Tasks.Task<AstuteServiceReference.ResponseOfArrayOfMessageHeaderTd6MonVm> GetCombinedMessageHeaderAsync(System.Guid messageId)
        {
            return base.Channel.GetCombinedMessageHeaderAsync(messageId);
        }
        
        public System.Threading.Tasks.Task<AstuteServiceReference.ResponseOfArrayOfMessageContentTd6MonVm> GetCombinedMessageContentAsync(System.Guid messageId)
        {
            return base.Channel.GetCombinedMessageContentAsync(messageId);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        #if !NET6_0_OR_GREATER
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        #endif
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.WSHttpBinding_IAstuteServiceV3))
            {
                System.ServiceModel.WSHttpBinding result = new System.ServiceModel.WSHttpBinding();
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.SecurityMode.TransportWithMessageCredential;
                result.Security.Transport.ClientCredentialType = System.ServiceModel.HttpClientCredentialType.None;
                result.Security.Message.ClientCredentialType = System.ServiceModel.MessageCredentialType.UserName;
                result.Security.Message.EstablishSecurityContext = false;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.WSHttpBinding_IAstuteServiceV3))
            {
                return new System.ServiceModel.EndpointAddress("https://uat.astutefse.com/online/ccp_astuteservicev3");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return AstuteServiceV3Client.GetBindingForEndpoint(EndpointConfiguration.WSHttpBinding_IAstuteServiceV3);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return AstuteServiceV3Client.GetEndpointAddress(EndpointConfiguration.WSHttpBinding_IAstuteServiceV3);
        }
        
        public enum EndpointConfiguration
        {
            
            WSHttpBinding_IAstuteServiceV3,
        }
    }
}
